export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_GRADE_BEGIN = 'FETCH_USER_GRADE_BEGIN';
export const FETCH_USER_GRADE_FAILURE = 'FETCH_USER_GRADE_FAILURE';
export const FETCH_USER_GRADE_SUCCESS = 'FETCH_USER_GRADE_SUCCESS';

export const FETCH_SHIFTS_PENDING = 'FETCH_SHIFTS_PENDING';
export const FETCH_SHIFTS_FAILURE = 'FETCH_SHIFTS_FAILURE';
export const FETCH_SHIFTS_SUCCESS = 'FETCH_SHIFTS_SUCCESS';

export const FETCH_TEAMS_PENDING = 'FETCH_TEAMS_PENDING';
export const FETCH_TEAMS_FAILURE = 'FETCH_TEAMS_FAILURE';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';

export const FETCH_STAFF_BEGIN = 'FETCH_STAFF_BEGIN'
export const FETCH_STAFF_FAILURE = 'FETCH_STAFF_FAILURE'
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS'

export const REPORT_STAFF_BEGIN = 'REPORT_STAFF_BEGIN'
export const REPORT_STAFF_FAILURE = 'REPORT_STAFF_FAILURE'
export const REPORT_STAFF_SUCCESS = 'REPORT_STAFF_SUCCESS'

export const CURRENT_SHIFT_BEGIN = 'CURRENT_SHIFT_BEGIN'
export const CURRENT_SHIFT_FAILURE = 'CURRENT_SHIFT_FAILURE'
export const CURRENT_SHIFT_SUCCESS = 'CURRENT_SHIFT_SUCCESS'


export const FETCH_ENTREPRISE_SUCCESS = 'FETCH_ENTREPRISE_SUCCESS';
export const FETCH_ENTREPRISE_BEGIN = 'FETCH_ENTREPRISE_BEGIN';
export const FETCH_ENTREPRISE_FAILURE = 'FETCH_ENTREPRISE_FAILURE';


export const FETCH_ENTREPRISEID_SUCCESS = 'FETCH_ENTREPRISEID_SUCCESS';
export const FETCH_ENTREPRISEID_BEGIN = 'FETCH_ENTREPRISEID_BEGIN';
export const FETCH_ENTREPRISEID_FAILURE = 'FETCH_ENTREPRISEID_FAILURE';


export const FETCH_ADDENTREPRISE_BEGIN='FETCH_ADDENTREPRISE_BEGIN';
export const FETCH_ADDENTREPRISE_SUCCESS='FETCH_ADDENTREPRISE_SUCCESS';
export const FETCH_ADDENTREPRISE_FAILURE='FETCH_ADDENTREPRISE_FAILURE';


export const FETCH_UPDATEENTREPRISE_BEGIN='FETCH_UPDATEENTREPRISE_BEGIN';
export const FETCH_UPDATEENTREPRISE_SUCCESS='FETCH_UPDATEENTREPRISE_SUCCESS';
export const FETCH_UPDATEENTREPRISE_FAILURE='FETCH_UPDATEENTREPRISE_FAILURE';


export const FETCH_DELETEENTREPRISE_BEGIN='FETCH_DELETEENTREPRISE_BEGIN';
export const FETCH_DELETEENTREPRISE_SUCCESS='FETCH_DELETEENTREPRISE_SUCCESS';
export const FETCH_DELETEENTREPRISE_FAILURE='FETCH_DELETEENTREPRISE_FAILURE';




export const FETCH_FILIALE_SUCCESS = 'FETCH_FILIALE_SUCCESS '
export const FETCH_FILIALE_BEGIN = 'FETCH_FILIALE_BEGIN '
export const FETCH_FILIALE_FAILURE = 'FETCH_FILIALE_FAILURE '

export const FETCH_ADDFILIALE_BEGIN = 'FETCH_ADDFILIALE_BEGIN '
export const FETCH_ADDFILIALE_SUCCESS = 'FETCH_ADDFILIALE_SUCCESS '
export const FETCH_ADDFILIALE_FAILURE = 'FETCH_ADDFILIALE_FAILURE '


export const FETCH_UPDATEFILIALE_BEGIN = 'FETCH_UPDATEFILIALE_BEGIN '
export const FETCH_UPDATEFILIALE_SUCCESS = 'FETCH_UPDATEFILIALE_SUCCESS '
export const FETCH_UPDATEFILIALE_FAILURE = 'FETCH_UPDATEFILIALE_FAILURE '

export const FETCH_DELETEFILIALE_BEGIN = 'FETCH_DELETEFILIALE_BEGIN '
export const FETCH_DELETEFILIALE_SUCCESS = 'FETCH_DELETEFILIALE_SUCCESS '
export const FETCH_DELETEFILIALE_FAILURE = 'FETCH_DELETEFILIALE_FAILURE '

export const FETCH_FILIALEEID_SUCCESS = 'FETCH_FILIALEEID_SUCCESS '
export const FETCH_FILIALEEID_BEGIN = 'FETCH_FILIALEEID_BEGIN '
export const FETCH_FILIALEEID_FAILURE = 'FETCH_FILIALEEID_FAILURE '


export const FETCH_ADDFILIALEE_BEGIN = 'FETCH_ADDFILIALEE_BEGIN'
export const FETCH_ADDFILIALEE_SUCCESS = 'FETCH_ADDFILIALEE_SUCCESS'
export const FETCH_ADDFILIALEE_FAILURE = 'FETCH_ADDFILIALEE_FAILURE' 




export const FETCH_PROJET_SUCCESS = 'FETCH_PROJET_SUCCESS '
export const FETCH_PROJET_BEGIN = 'FETCH_PROJET_BEGIN '
export const FETCH_PROJET_FAILURE = 'FETCH_PROJET_FAILURE' 


export const FETCH_ADDPROJET_BEGIN = 'FETCH_ADDPROJET_BEGIN '
export const FETCH_ADDPROJET_SUCCESS = 'FETCH_ADDPROJET_SUCCESS '
export const FETCH_ADDPROJET_FAILURE = 'FETCH_ADDPROJET_FAILURE'


export const FETCH_UPDATEPROJET_BEGIN = 'FETCH_UPDATEPROJET_BEGIN'
export const FETCH_UPDATEPROJET_SUCCESS = 'FETCH_UPDATEPROJET_SUCCESS'
export const FETCH_UPDATEPROJET_FAILURE = 'FETCH_UPDATEPROJET_FAILURE'



export const FETCH_DELETEPROJET_BEGIN = 'FETCH_DELETEPROJET_BEGIN'
export const FETCH_DELETEPROJET_SUCCESS = 'FETCH_DELETEPROJET_SUCCESS'
export const FETCH_DELETEPROJET_FAILURE = 'FETCH_DELETEPROJET_FAILURE'


export const FETCH_PROJETID_SUCCESS = 'FETCH_PROJETEID_SUCCESS'
export const FETCH_PROJETID_BEGIN = 'FETCH_PROJETEID_BEGIN'
export const FETCH_PROJETID_FAILURE = 'FETCH_PROJETEID_FAILURE'


export const FETCH_ADDFILIALEPRO_BEGIN = 'FETCH_ADDFILIALEPRO_BEGIN'
export const FETCH_ADDFILIALEPRO_SUCCES = 'FETCH_ADDFILIALEPRO_SUCCES'
export const FETCH_ADDFILIALEPRO_FAILURE = 'FETCH_ADDFILIALEPRO_FAILURE'

export const FETCH_ADDPROJETCOLAB_SUCCESS = 'FETCH_ADDPROJETCOLAB_SUCCESS'
export const FETCH_ADDPROJETCOLAB_BEGIN = 'FETCH_ADDPROOJETCOLAB_SUCCESS'
export const FETCH_ADDPROJETCOLAB_FAILURE = 'FETCH_ADDPROJETCOLAB_FAILURE'

export const FETCH_ADDPROJETTECH_SUCCESS = 'FETCH_ADDPROJETTECH_SUCCESS'
export const FETCH_ADDPROJETTECH_BEGIN = 'FETCH_ADDPROJETTECH_BEGIN'
export const FETCH_ADDPROJETTECH_FAILURE = 'FETCH_ADDPROJETTECH_FAILURE'

export const FETCH_COLLABORATEUR_SUCCESS = 'FETCH_COLLABORATEUR_SUCCESS'
export const FETCH_COLLABORATEUR_BEGIN = 'FETCH_COLLABORATEUR_BEGIN'
export const FETCH_COLLABORATEUR_FAILURE = 'FETCH_COLLABORATEUR_FAILURE' 

export const FETCH_ADDCOLLABORATEUR_BEGIN = 'FETCH_ADDCOLLABORATEUR_BEGIN'
export const FETCH_ADDCOLLABORATEUR_SUCCESS = 'FETCH_ADDCOLLABORATEUR_SUCCESS'
export const FETCH_ADDCOLLABORATEUR_FAILURE = 'FETCH_ADDCOLLABORATEUR_FAILURE' 

export const FETCH_UPDATECOLLABORATEUR_BEGIN = 'FETCH_UPDATECOLLABORATEUR_BEGIN'
export const FETCH_UPDATECOLLABORATEUR_SUCCESS = 'FETCH_UPDATECOLLABORATEUR_SUCCESS'
export const FETCH_UPDATECOLLABORATEUR_FAILURE = 'FETCH_UPDATECOLLABORATEUR_FAILURE' 

export const FETCH_DELETECOLLABORATEUR_BEGIN = 'FETCH_DELETECOLLABORATEUR_BEGIN '
export const FETCH_DELETECOLLABORATEUR_SUCCESS = 'FETCH_DELETECOLLABORATEUR_SUCCESS'
export const FETCH_DELETECOLLABORATEUR_FAILURE = 'FETCH_DELETECOLLABORATEUR_FAILURE'

export const FETCH_COLLABORATEURID_SUCCESS = 'FETCH_COLLABORATEURID_SUCCESS'
export const FETCH_COLLABORATEURID_BEGIN = 'FETCH_COLLABORATEURID_BEGIN'
export const FETCH_COLLABORATEURID_FAILURE = 'FETCH_COLLABORATEURID_FAILURE'


export const FETCH_TECHNOLOGIE_BEGIN = 'FETCH_TECHNOLOGIE_BEGIN '
export const FETCH_TECHNOLOGIE_SUCCESS = 'FETCH_TECHNOLOGIE_SUCCESS '
export const FETCH_TECHNOLOGIE_FAILURE = 'FETCH_TECHNOLOGIE_FAILURE' 


export const FETCH_ADDTECHNOLOGIE_BEGIN = 'FETCH_ADDTECHNOLOGIE_BEGIN '
export const FETCH_ADDTECHNOLOGIE_SUCCESS = 'FETCH_ADDTECHNOLOGIE_SUCCESS '
export const FETCH_ADDTECHNOLOGIE_FAILURE = 'FETCH_ADDTECHNOLOGIE_FAILURE'


export const FETCH_UPDATETECHNOLOGIE_BEGIN = 'FETCH_UPDATETECHNOLOGIE_BEGIN '
export const FETCH_UPDATETECHNOLOGIE_SUCCESS = 'FETCH_UPDATETECHNOLOGIE_SUCCESS '
export const FETCH_UPDATETECHNOLOGIE_FAILURE = 'FETCH_UPDATETECHNOLOGIE_FAILURE'


export const FETCH_DELETETECHNOLOGIE_BEGIN = 'FETCH_DELETETECHNOLOGIE_BEGIN '
export const FETCH_DELETETECHNOLOGIE_SUCCESS = 'FETCH_DELETETECHNOLOGIE_SUCCESS '
export const FETCH_DELETETECHNOLOGIE_FAILURE = 'FETCH_DELETETECHNOLOGIE_FAILURE'


export const FETCH_TECHNOLOGIEID_BEGIN = 'FETCH_TECHNOLOGIEID_BEGIN '
export const FETCH_TECHNOLOGIEID_SUCCESS = 'FETCH_TECHNOLOGIEID_SUCCESS '
export const FETCH_TECHNOLOGIEID_FAILURE = 'FETCH_TECHNOLOGIEID_FAILURE'

